name: CD

on: push

jobs:
  deploy-test-pypi:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Make distrib
      run: |
        python3 -m pip install wheel
        bash make_distrib.sh

    - name: Upload to TestPyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
